// app/layout.tsx

import localFont from 'next/font/local'
import './globals.css';
// استيراد خط Geist Sans العادي
const geistSans = localFont({
  src: [
    {
      path: '../public/fonts/Geist-Regular.woff2', // غيري هذا المسار ليطابق اسم الملف الذي لديكِ
      weight: '400', // هذا الوزن العادي
    },
    {
      path: '../public/fonts/Geist-Bold.woff2', // غيري هذا المسار ليطابق اسم الملف الذي لديكِ
      weight: '700', // هذا الوزن العريض
    },
    // أضيفي هنا أي أوزان أخرى (مثل Light, Medium, Thin)
  ],
  variable: '--font-geist-sans',
})

// استيراد خط Geist Mono
const geistMono = localFont({
  src: [
    {
      path: '../public/fonts/GeistMono-Regular.woff2', // غيري هذا المسار ليطابق اسم الملف الذي لديكِ
      weight: '400',
    },
    {
      path: '../public/fonts/GeistMono-Bold.woff2', // غيري هذا المسار ليطابق اسم الملف الذي لديكِ
      weight: '700',
    },
    // أضيفي هنا أي أوزان أخرى
  ],
  variable: '--font-geist-mono',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  )
}